"""
Thumbnail Layout Presets - 7 distinct visual styles for variety.

Each layout is a complete thumbnail_config override that gets deep-merged
into the base config. The AI selects a layout based on the video's mood/theme.
"""

LAYOUTS = {
    "luminoso": {
        "name": "Luminoso",
        "description": "Brillante, aireado, cálido. Como luz de mañana. La imagen se ve claramente. Ideal para temas de esperanza y luz.",
        "mood_tags": ["esperanza", "gozo", "templo", "bendición", "oración", "luz", "resurrección", "fe", "promesa"],
        "config": {
            "thumbnail": {
                "gradient_overlay": {
                    "enabled": True,
                    "direction": "top_to_bottom",
                    "start_y_percent": 0,
                    "max_opacity": 140,
                    "color": [255, 248, 230],
                    "curve_exponent": 2.0,
                },
                "bottom_band": {
                    "enabled": True,
                    "height_percent": 20,
                    "color": [255, 255, 255],
                    "opacity": 175,
                },
                "color_wash": {"enabled": False},
                "vignette": {"enabled": False},
                "title": {
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 78,
                    "color": "#1A2744",
                    "highlight_color": "#B8860B",
                    "stroke_width": 0,
                    "stroke_color": "#000000",
                    "shadow_offset": [2, 2],
                    "shadow_color": "#00000040",
                    "position_y_percent": 73,
                    "align": "center",
                    "margin_left": 40,
                    "line_spacing": 10,
                    "max_lines": 2,
                    "max_width_percent": 90,
                },
                "accent_element": {
                    "enabled": True,
                    "type": "divider_below",
                    "color": "#B8860B",
                    "height": 2,
                    "width_percent": 30,
                    "margin_from_title": 12,
                },
                "accent_line": {"enabled": False},
                "scripture_badge": {
                    "enabled": True,
                    "font": "Montserrat-Medium.ttf",
                    "font_size": 24,
                    "text_color": "#4A5568",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "align": "center",
                    "margin_bottom": 28,
                    "corner_radius": 0,
                },
                "branding": {
                    "enabled": True,
                    "position": "top_right",
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 22,
                    "text_color": "#1A2744",
                    "background_color": "#FFFFFFA0",
                    "padding_h": 14,
                    "padding_v": 6,
                    "margin_right": 30,
                    "margin_bottom": 30,
                    "corner_radius": 6,
                },
            }
        },
    },

    "dramatico": {
        "name": "Dramático",
        "description": "Cinemático, intenso, alto contraste. Gradiente azul marino profundo con viñeta. Para temas de conflicto y advertencia.",
        "mood_tags": ["guerra", "juicio", "destrucción", "advertencia", "apostasía", "conflicto", "intenso", "castigo", "diluvio"],
        "config": {
            "thumbnail": {
                "gradient_overlay": {
                    "enabled": True,
                    "direction": "bottom_to_top",
                    "start_y_percent": 20,
                    "max_opacity": 240,
                    "color": [10, 18, 38],
                    "curve_exponent": 1.3,
                },
                "bottom_band": {"enabled": False},
                "color_wash": {"enabled": False},
                "vignette": {
                    "enabled": True,
                    "strength": 0.4,
                    "color": [5, 10, 25],
                },
                "title": {
                    "font": "Montserrat-ExtraBold.ttf",
                    "font_size": 90,
                    "color": "#FFFFFF",
                    "highlight_color": "#FF3333",
                    "stroke_width": 6,
                    "stroke_color": "#0A1628",
                    "shadow_offset": [4, 4],
                    "shadow_color": "#000000AA",
                    "position_y_percent": 55,
                    "align": "left",
                    "margin_left": 60,
                    "line_spacing": 12,
                    "max_lines": 3,
                    "max_width_percent": 85,
                },
                "accent_element": {
                    "enabled": True,
                    "type": "line_above",
                    "color": "#FF3333",
                    "height": 6,
                    "width_percent": 30,
                    "margin_left": 60,
                    "margin_bottom_from_title": 14,
                },
                "accent_line": {"enabled": False},
                "scripture_badge": {
                    "enabled": True,
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 28,
                    "text_color": "#FFFFFF",
                    "background_color": "#8B000099",
                    "padding_h": 16,
                    "padding_v": 6,
                    "align": "left",
                    "margin_left": 60,
                    "margin_bottom": 35,
                    "corner_radius": 6,
                },
                "branding": {
                    "enabled": True,
                    "position": "bottom_right",
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 26,
                    "text_color": "#FFD700",
                    "background_color": "#0A162899",
                    "padding_h": 14,
                    "padding_v": 6,
                    "margin_right": 35,
                    "margin_bottom": 35,
                    "corner_radius": 6,
                },
            }
        },
    },

    "celestial": {
        "name": "Celestial",
        "description": "Elegante, regio, sagrado. Tipografía serif con marco dorado. Como la portada de un libro de escrituras.",
        "mood_tags": ["doctrina", "escritura", "convenio", "templo", "ordenanza", "sagrado", "revelación", "eternidad"],
        "config": {
            "thumbnail": {
                "gradient_overlay": {
                    "enabled": True,
                    "direction": "bottom_to_top",
                    "start_y_percent": 30,
                    "max_opacity": 210,
                    "color": [20, 12, 40],
                    "curve_exponent": 1.6,
                },
                "bottom_band": {"enabled": False},
                "color_wash": {"enabled": False},
                "vignette": {"enabled": False},
                "title": {
                    "font": "Cinzel-Bold.ttf",
                    "font_size": 72,
                    "color": "#F5F0E8",
                    "highlight_color": "#FFD700",
                    "stroke_width": 4,
                    "stroke_color": "#1A0C28",
                    "shadow_offset": [3, 3],
                    "shadow_color": "#00000080",
                    "position_y_percent": 62,
                    "align": "center",
                    "margin_left": 50,
                    "line_spacing": 14,
                    "max_lines": 3,
                    "max_width_percent": 85,
                },
                "accent_element": {
                    "enabled": True,
                    "type": "frame",
                    "color": "#FFD700",
                    "height": 2,
                    "width_percent": 45,
                    "margin_from_title": 16,
                },
                "accent_line": {"enabled": False},
                "scripture_badge": {
                    "enabled": True,
                    "font": "Montserrat-Medium.ttf",
                    "font_size": 26,
                    "text_color": "#FFD700",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "align": "center",
                    "margin_bottom": 30,
                    "corner_radius": 0,
                },
                "branding": {
                    "enabled": True,
                    "position": "top_left",
                    "font": "Montserrat-Medium.ttf",
                    "font_size": 22,
                    "text_color": "#F5F0E880",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "margin_right": 35,
                    "margin_bottom": 30,
                    "corner_radius": 0,
                },
            }
        },
    },

    "profeta": {
        "name": "Profeta",
        "description": "Foco dividido: texto a la izquierda, personaje visible a la derecha. Gradiente lateral. Para videos sobre personas específicas.",
        "mood_tags": ["profeta", "líder", "persona", "héroe", "pionero", "biografía", "personaje", "misionero", "apóstol"],
        "config": {
            "thumbnail": {
                "gradient_overlay": {
                    "enabled": True,
                    "direction": "left_to_right",
                    "start_y_percent": 0,
                    "max_opacity": 230,
                    "color": [12, 20, 35],
                    "curve_exponent": 1.4,
                },
                "bottom_band": {"enabled": False},
                "color_wash": {"enabled": False},
                "vignette": {"enabled": False},
                "title": {
                    "font": "Montserrat-ExtraBold.ttf",
                    "font_size": 76,
                    "color": "#FFFFFF",
                    "highlight_color": "#F0A030",
                    "stroke_width": 4,
                    "stroke_color": "#0C1423",
                    "shadow_offset": [3, 3],
                    "shadow_color": "#00000090",
                    "position_y_percent": 40,
                    "align": "left",
                    "margin_left": 55,
                    "line_spacing": 10,
                    "max_lines": 3,
                    "max_width_percent": 42,
                },
                "accent_element": {
                    "enabled": True,
                    "type": "vertical_line",
                    "color": "#F0A030",
                    "width": 4,
                    "margin_left": 40,
                    "start_y_percent": 25,
                    "height_percent": 50,
                },
                "accent_line": {"enabled": False},
                "scripture_badge": {
                    "enabled": True,
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 26,
                    "text_color": "#FFFFFF",
                    "background_color": "#E8772299",
                    "padding_h": 16,
                    "padding_v": 6,
                    "align": "left",
                    "margin_left": 55,
                    "margin_bottom": 35,
                    "corner_radius": 6,
                },
                "branding": {
                    "enabled": True,
                    "position": "top_left",
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 22,
                    "text_color": "#FFFFFFCC",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "margin_right": 35,
                    "margin_bottom": 30,
                    "corner_radius": 0,
                },
            }
        },
    },

    "esperanza": {
        "name": "Esperanza",
        "description": "Cálido, invitante, como luz de atardecer. Tinte dorado sutil sobre la imagen. Para temas devocionales y de consuelo.",
        "mood_tags": ["consuelo", "paz", "sanación", "familia", "testimonio", "devoción", "calidez", "amor", "misericordia"],
        "config": {
            "thumbnail": {
                "gradient_overlay": {
                    "enabled": True,
                    "direction": "bottom_to_top",
                    "start_y_percent": 35,
                    "max_opacity": 200,
                    "color": [45, 28, 12],
                    "curve_exponent": 1.8,
                },
                "bottom_band": {"enabled": False},
                "color_wash": {
                    "enabled": True,
                    "color": [255, 200, 120],
                    "opacity": 25,
                },
                "vignette": {"enabled": False},
                "title": {
                    "font": "Montserrat-SemiBold.ttf",
                    "font_size": 80,
                    "color": "#FFF8F0",
                    "highlight_color": "#FFD700",
                    "stroke_width": 3,
                    "stroke_color": "#2D1C0C",
                    "shadow_offset": [3, 3],
                    "shadow_color": "#00000060",
                    "position_y_percent": 60,
                    "align": "left",
                    "margin_left": 60,
                    "line_spacing": 12,
                    "max_lines": 3,
                    "max_width_percent": 85,
                },
                "accent_element": {
                    "enabled": True,
                    "type": "diamond",
                    "color": "#FFD700",
                    "size": 18,
                    "margin_left": 60,
                },
                "accent_line": {"enabled": False},
                "scripture_badge": {
                    "enabled": True,
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 26,
                    "text_color": "#FFF0D0",
                    "background_color": "#6B3A1F99",
                    "padding_h": 16,
                    "padding_v": 6,
                    "align": "left",
                    "margin_left": 60,
                    "margin_bottom": 35,
                    "corner_radius": 6,
                },
                "branding": {
                    "enabled": True,
                    "position": "bottom_right",
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 26,
                    "text_color": "#FFD700",
                    "background_color": "#6B3A1F99",
                    "padding_h": 14,
                    "padding_v": 6,
                    "margin_right": 35,
                    "margin_bottom": 35,
                    "corner_radius": 6,
                },
            }
        },
    },

    "impacto": {
        "name": "Impacto",
        "description": "Moderno, audaz, estilo YouTube popular. Bloque sólido de color abajo con texto grande. Máximo CTR.",
        "mood_tags": ["lista", "señales", "secretos", "sorprendente", "datos", "números", "clickable", "audaz", "viral"],
        "config": {
            "thumbnail": {
                "gradient_overlay": {"enabled": False},
                "bottom_band": {
                    "enabled": True,
                    "height_percent": 32,
                    "color": [0, 45, 100],
                    "opacity": 230,
                    "top_line": {
                        "enabled": True,
                        "color": "#FFFFFF",
                        "height": 2,
                    },
                },
                "color_wash": {"enabled": False},
                "vignette": {"enabled": False},
                "title": {
                    "font": "Montserrat-ExtraBold.ttf",
                    "font_size": 88,
                    "color": "#FFFFFF",
                    "highlight_color": "#FFE500",
                    "stroke_width": 0,
                    "stroke_color": "#000000",
                    "shadow_offset": [0, 0],
                    "shadow_color": "#00000000",
                    "position_y_percent": 72,
                    "align": "center",
                    "margin_left": 40,
                    "line_spacing": 8,
                    "max_lines": 2,
                    "max_width_percent": 92,
                },
                "accent_element": {"enabled": False},
                "accent_line": {"enabled": False},
                "scripture_badge": {
                    "enabled": True,
                    "font": "Montserrat-Medium.ttf",
                    "font_size": 22,
                    "text_color": "#FFFFFF80",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "align": "right",
                    "margin_left": 60,
                    "margin_bottom": 20,
                    "margin_right": 40,
                    "corner_radius": 0,
                },
                "branding": {
                    "enabled": True,
                    "position": "bottom_left",
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 24,
                    "text_color": "#FFE500",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "margin_right": 35,
                    "margin_bottom": 20,
                    "margin_left": 40,
                    "corner_radius": 0,
                },
            }
        },
    },

    "minimalista": {
        "name": "Minimalista",
        "description": "Limpio, quieto, editorial. Gradiente muy sutil, texto pequeño abajo. Deja que la imagen sagrada hable por sí sola.",
        "mood_tags": ["reflexión", "sabbath", "quietud", "simple", "verdad", "meditación", "personal", "silencio", "contemplación"],
        "config": {
            "thumbnail": {
                "gradient_overlay": {
                    "enabled": True,
                    "direction": "bottom_to_top",
                    "start_y_percent": 50,
                    "max_opacity": 150,
                    "color": [30, 30, 35],
                    "curve_exponent": 2.5,
                },
                "bottom_band": {"enabled": False},
                "color_wash": {"enabled": False},
                "vignette": {"enabled": False},
                "title": {
                    "font": "Montserrat-Medium.ttf",
                    "font_size": 68,
                    "color": "#FFFFFF",
                    "highlight_color": "#7CB9E8",
                    "stroke_width": 2,
                    "stroke_color": "#1E1E23",
                    "shadow_offset": [2, 2],
                    "shadow_color": "#00000050",
                    "position_y_percent": 76,
                    "align": "left",
                    "margin_left": 50,
                    "line_spacing": 10,
                    "max_lines": 2,
                    "max_width_percent": 80,
                },
                "accent_element": {"enabled": False},
                "accent_line": {"enabled": False},
                "scripture_badge": {
                    "enabled": True,
                    "font": "Montserrat-Medium.ttf",
                    "font_size": 22,
                    "text_color": "#AAAAAA",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "align": "left",
                    "margin_left": 50,
                    "margin_bottom": 25,
                    "corner_radius": 0,
                },
                "branding": {
                    "enabled": True,
                    "position": "bottom_right",
                    "font": "Montserrat-Medium.ttf",
                    "font_size": 22,
                    "text_color": "#AAAAAA",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "margin_right": 35,
                    "margin_bottom": 25,
                    "corner_radius": 0,
                },
            }
        },
    },
}


def get_layout(layout_name: str) -> dict:
    """Get a layout preset by name. Returns the full layout dict including metadata."""
    if layout_name not in LAYOUTS:
        available = ", ".join(LAYOUTS.keys())
        raise ValueError(f"Unknown layout '{layout_name}'. Available: {available}")
    return LAYOUTS[layout_name]


def get_layout_config(layout_name: str) -> dict:
    """Get just the config portion of a layout for merging into thumbnail_config."""
    return get_layout(layout_name)["config"]


def list_layouts() -> list:
    """Return a summary list of all layouts for the AI to choose from."""
    result = []
    for key, layout in LAYOUTS.items():
        result.append({
            "id": key,
            "name": layout["name"],
            "description": layout["description"],
            "mood_tags": layout["mood_tags"],
        })
    return result
