"""
Thumbnail Layout Presets - 7 distinct visual styles for variety.

Each layout is a complete thumbnail_config override that gets deep-merged
into the base config. The AI selects a layout based on the video's mood/theme.

DESIGN PHILOSOPHY:
All layouts share the elegant left-side gradient + left-aligned text approach.
The image is always clearly visible on the right side. Each layout differs in
color palette, font weight, accent elements, and mood — not in structure.
"""

LAYOUTS = {
    "luminoso": {
        "name": "Luminoso",
        "description": "Brillante, aireado, cálido. Gradiente suave de tonos crema a la izquierda. La imagen se ve claramente a la derecha. Ideal para temas de esperanza y luz.",
        "mood_tags": ["esperanza", "gozo", "templo", "bendición", "oración", "luz", "resurrección", "fe", "promesa"],
        "config": {
            "thumbnail": {
                "gradient_overlay": {
                    "enabled": True,
                    "direction": "left_to_right",
                    "start_y_percent": 0,
                    "max_opacity": 240,
                    "color": [250, 240, 220],
                    "curve_exponent": 1.3,
                },
                "bottom_band": {"enabled": False},
                "color_wash": {"enabled": False},
                "vignette": {"enabled": False},
                "title": {
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 78,
                    "color": "#1A2744",
                    "highlight_color": "#B8860B",
                    "stroke_width": 0,
                    "stroke_color": "#000000",
                    "shadow_offset": [2, 2],
                    "shadow_color": "#00000030",
                    "position_y_percent": 40,
                    "align": "left",
                    "margin_left": 55,
                    "line_spacing": 10,
                    "max_lines": 3,
                    "max_width_percent": 50,
                },
                "accent_element": {
                    "enabled": True,
                    "type": "vertical_line",
                    "color": "#B8860B",
                    "width": 4,
                    "margin_left": 40,
                    "start_y_percent": 25,
                    "height_percent": 50,
                },
                "accent_line": {"enabled": False},
                "scripture_badge": {
                    "enabled": True,
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 26,
                    "text_color": "#1A2744",
                    "background_color": "#B8860B40",
                    "padding_h": 16,
                    "padding_v": 6,
                    "align": "left",
                    "margin_left": 55,
                    "margin_bottom": 35,
                    "corner_radius": 6,
                },
                "branding": {
                    "enabled": True,
                    "position": "top_left",
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 22,
                    "text_color": "#1A2744CC",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "margin_right": 35,
                    "margin_bottom": 30,
                    "corner_radius": 0,
                },
            }
        },
    },

    "dramatico": {
        "name": "Dramático",
        "description": "Cinemático, intenso, alto contraste. Gradiente azul marino profundo a la izquierda con viñeta. Para temas de conflicto y advertencia.",
        "mood_tags": ["guerra", "juicio", "destrucción", "advertencia", "apostasía", "conflicto", "intenso", "castigo", "diluvio"],
        "config": {
            "thumbnail": {
                "gradient_overlay": {
                    "enabled": True,
                    "direction": "left_to_right",
                    "start_y_percent": 0,
                    "max_opacity": 245,
                    "color": [10, 18, 38],
                    "curve_exponent": 1.3,
                },
                "bottom_band": {"enabled": False},
                "color_wash": {"enabled": False},
                "vignette": {
                    "enabled": True,
                    "strength": 0.3,
                    "color": [5, 10, 25],
                },
                "title": {
                    "font": "Montserrat-ExtraBold.ttf",
                    "font_size": 82,
                    "color": "#FFFFFF",
                    "highlight_color": "#FF3333",
                    "stroke_width": 5,
                    "stroke_color": "#0A1628",
                    "shadow_offset": [4, 4],
                    "shadow_color": "#000000AA",
                    "position_y_percent": 40,
                    "align": "left",
                    "margin_left": 55,
                    "line_spacing": 12,
                    "max_lines": 3,
                    "max_width_percent": 50,
                },
                "accent_element": {
                    "enabled": True,
                    "type": "vertical_line",
                    "color": "#FF3333",
                    "width": 5,
                    "margin_left": 40,
                    "start_y_percent": 25,
                    "height_percent": 50,
                },
                "accent_line": {"enabled": False},
                "scripture_badge": {
                    "enabled": True,
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 26,
                    "text_color": "#FFFFFF",
                    "background_color": "#8B000099",
                    "padding_h": 16,
                    "padding_v": 6,
                    "align": "left",
                    "margin_left": 55,
                    "margin_bottom": 35,
                    "corner_radius": 6,
                },
                "branding": {
                    "enabled": True,
                    "position": "top_left",
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 22,
                    "text_color": "#FFFFFFCC",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "margin_right": 35,
                    "margin_bottom": 30,
                    "corner_radius": 0,
                },
            }
        },
    },

    "celestial": {
        "name": "Celestial",
        "description": "Elegante, regio, sagrado. Gradiente púrpura oscuro lateral con tipografía serif dorada. Como la portada de un libro de escrituras.",
        "mood_tags": ["doctrina", "escritura", "convenio", "templo", "ordenanza", "sagrado", "revelación", "eternidad"],
        "config": {
            "thumbnail": {
                "gradient_overlay": {
                    "enabled": True,
                    "direction": "left_to_right",
                    "start_y_percent": 0,
                    "max_opacity": 235,
                    "color": [20, 12, 40],
                    "curve_exponent": 1.4,
                },
                "bottom_band": {"enabled": False},
                "color_wash": {"enabled": False},
                "vignette": {"enabled": False},
                "title": {
                    "font": "Cinzel-Bold.ttf",
                    "font_size": 72,
                    "color": "#F5F0E8",
                    "highlight_color": "#FFD700",
                    "stroke_width": 4,
                    "stroke_color": "#1A0C28",
                    "shadow_offset": [3, 3],
                    "shadow_color": "#00000080",
                    "position_y_percent": 40,
                    "align": "left",
                    "margin_left": 55,
                    "line_spacing": 14,
                    "max_lines": 3,
                    "max_width_percent": 50,
                },
                "accent_element": {
                    "enabled": True,
                    "type": "vertical_line",
                    "color": "#FFD700",
                    "width": 3,
                    "margin_left": 40,
                    "start_y_percent": 25,
                    "height_percent": 50,
                },
                "accent_line": {"enabled": False},
                "scripture_badge": {
                    "enabled": True,
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 26,
                    "text_color": "#FFD700",
                    "background_color": "#1A0C2899",
                    "padding_h": 16,
                    "padding_v": 6,
                    "align": "left",
                    "margin_left": 55,
                    "margin_bottom": 35,
                    "corner_radius": 6,
                },
                "branding": {
                    "enabled": True,
                    "position": "top_left",
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 22,
                    "text_color": "#F5F0E880",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "margin_right": 35,
                    "margin_bottom": 30,
                    "corner_radius": 0,
                },
            }
        },
    },

    "profeta": {
        "name": "Profeta",
        "description": "Foco dividido: texto a la izquierda, personaje visible a la derecha. Gradiente lateral. Para videos sobre personas específicas.",
        "mood_tags": ["profeta", "líder", "persona", "héroe", "pionero", "biografía", "personaje", "misionero", "apóstol"],
        "config": {
            "thumbnail": {
                "gradient_overlay": {
                    "enabled": True,
                    "direction": "left_to_right",
                    "start_y_percent": 0,
                    "max_opacity": 230,
                    "color": [12, 20, 35],
                    "curve_exponent": 1.4,
                },
                "bottom_band": {"enabled": False},
                "color_wash": {"enabled": False},
                "vignette": {"enabled": False},
                "title": {
                    "font": "Montserrat-ExtraBold.ttf",
                    "font_size": 76,
                    "color": "#FFFFFF",
                    "highlight_color": "#F0A030",
                    "stroke_width": 4,
                    "stroke_color": "#0C1423",
                    "shadow_offset": [3, 3],
                    "shadow_color": "#00000090",
                    "position_y_percent": 40,
                    "align": "left",
                    "margin_left": 55,
                    "line_spacing": 10,
                    "max_lines": 3,
                    "max_width_percent": 42,
                },
                "accent_element": {
                    "enabled": True,
                    "type": "vertical_line",
                    "color": "#F0A030",
                    "width": 4,
                    "margin_left": 40,
                    "start_y_percent": 25,
                    "height_percent": 50,
                },
                "accent_line": {"enabled": False},
                "scripture_badge": {
                    "enabled": True,
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 26,
                    "text_color": "#FFFFFF",
                    "background_color": "#E8772299",
                    "padding_h": 16,
                    "padding_v": 6,
                    "align": "left",
                    "margin_left": 55,
                    "margin_bottom": 35,
                    "corner_radius": 6,
                },
                "branding": {
                    "enabled": True,
                    "position": "top_left",
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 22,
                    "text_color": "#FFFFFFCC",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "margin_right": 35,
                    "margin_bottom": 30,
                    "corner_radius": 0,
                },
            }
        },
    },

    "esperanza": {
        "name": "Esperanza",
        "description": "Cálido, invitante, como luz de atardecer. Gradiente lateral en tonos cálidos oscuros. Para temas devocionales y de consuelo.",
        "mood_tags": ["consuelo", "paz", "sanación", "familia", "testimonio", "devoción", "calidez", "amor", "misericordia"],
        "config": {
            "thumbnail": {
                "gradient_overlay": {
                    "enabled": True,
                    "direction": "left_to_right",
                    "start_y_percent": 0,
                    "max_opacity": 235,
                    "color": [45, 28, 12],
                    "curve_exponent": 1.4,
                },
                "bottom_band": {"enabled": False},
                "color_wash": {
                    "enabled": True,
                    "color": [255, 200, 120],
                    "opacity": 20,
                },
                "vignette": {"enabled": False},
                "title": {
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 78,
                    "color": "#FFF8F0",
                    "highlight_color": "#FFD700",
                    "stroke_width": 3,
                    "stroke_color": "#2D1C0C",
                    "shadow_offset": [3, 3],
                    "shadow_color": "#00000060",
                    "position_y_percent": 40,
                    "align": "left",
                    "margin_left": 55,
                    "line_spacing": 12,
                    "max_lines": 3,
                    "max_width_percent": 50,
                },
                "accent_element": {
                    "enabled": True,
                    "type": "vertical_line",
                    "color": "#FFD700",
                    "width": 4,
                    "margin_left": 40,
                    "start_y_percent": 25,
                    "height_percent": 50,
                },
                "accent_line": {"enabled": False},
                "scripture_badge": {
                    "enabled": True,
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 26,
                    "text_color": "#FFF0D0",
                    "background_color": "#6B3A1F99",
                    "padding_h": 16,
                    "padding_v": 6,
                    "align": "left",
                    "margin_left": 55,
                    "margin_bottom": 35,
                    "corner_radius": 6,
                },
                "branding": {
                    "enabled": True,
                    "position": "top_left",
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 22,
                    "text_color": "#FFD700CC",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "margin_right": 35,
                    "margin_bottom": 30,
                    "corner_radius": 0,
                },
            }
        },
    },

    "impacto": {
        "name": "Impacto",
        "description": "Moderno, audaz, alto impacto. Gradiente lateral negro sólido con acentos amarillos vibrantes. Máximo CTR para YouTube.",
        "mood_tags": ["lista", "señales", "secretos", "sorprendente", "datos", "números", "clickable", "audaz", "viral"],
        "config": {
            "thumbnail": {
                "gradient_overlay": {
                    "enabled": True,
                    "direction": "left_to_right",
                    "start_y_percent": 0,
                    "max_opacity": 250,
                    "color": [8, 8, 12],
                    "curve_exponent": 1.2,
                },
                "bottom_band": {"enabled": False},
                "color_wash": {"enabled": False},
                "vignette": {"enabled": False},
                "title": {
                    "font": "Montserrat-ExtraBold.ttf",
                    "font_size": 84,
                    "color": "#FFFFFF",
                    "highlight_color": "#FFE500",
                    "stroke_width": 5,
                    "stroke_color": "#080808",
                    "shadow_offset": [4, 4],
                    "shadow_color": "#000000BB",
                    "position_y_percent": 40,
                    "align": "left",
                    "margin_left": 55,
                    "line_spacing": 8,
                    "max_lines": 3,
                    "max_width_percent": 50,
                },
                "accent_element": {
                    "enabled": True,
                    "type": "vertical_line",
                    "color": "#FFE500",
                    "width": 6,
                    "margin_left": 40,
                    "start_y_percent": 25,
                    "height_percent": 50,
                },
                "accent_line": {"enabled": False},
                "scripture_badge": {
                    "enabled": True,
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 26,
                    "text_color": "#FFE500",
                    "background_color": "#1A1A1A99",
                    "padding_h": 16,
                    "padding_v": 6,
                    "align": "left",
                    "margin_left": 55,
                    "margin_bottom": 35,
                    "corner_radius": 6,
                },
                "branding": {
                    "enabled": True,
                    "position": "top_left",
                    "font": "Montserrat-Bold.ttf",
                    "font_size": 22,
                    "text_color": "#FFE500CC",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "margin_right": 35,
                    "margin_bottom": 30,
                    "corner_radius": 0,
                },
            }
        },
    },

    "minimalista": {
        "name": "Minimalista",
        "description": "Limpio, quieto, editorial. Gradiente lateral suave y sutil. Texto delicado a la izquierda, la imagen sagrada domina.",
        "mood_tags": ["reflexión", "sabbath", "quietud", "simple", "verdad", "meditación", "personal", "silencio", "contemplación"],
        "config": {
            "thumbnail": {
                "gradient_overlay": {
                    "enabled": True,
                    "direction": "left_to_right",
                    "start_y_percent": 0,
                    "max_opacity": 210,
                    "color": [30, 30, 35],
                    "curve_exponent": 1.5,
                },
                "bottom_band": {"enabled": False},
                "color_wash": {"enabled": False},
                "vignette": {"enabled": False},
                "title": {
                    "font": "Montserrat-Medium.ttf",
                    "font_size": 70,
                    "color": "#FFFFFF",
                    "highlight_color": "#7CB9E8",
                    "stroke_width": 2,
                    "stroke_color": "#1E1E23",
                    "shadow_offset": [2, 2],
                    "shadow_color": "#00000050",
                    "position_y_percent": 40,
                    "align": "left",
                    "margin_left": 55,
                    "line_spacing": 10,
                    "max_lines": 3,
                    "max_width_percent": 50,
                },
                "accent_element": {
                    "enabled": True,
                    "type": "vertical_line",
                    "color": "#7CB9E8",
                    "width": 2,
                    "margin_left": 42,
                    "start_y_percent": 28,
                    "height_percent": 44,
                },
                "accent_line": {"enabled": False},
                "scripture_badge": {
                    "enabled": True,
                    "font": "Montserrat-Medium.ttf",
                    "font_size": 24,
                    "text_color": "#CCCCCC",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "align": "left",
                    "margin_left": 55,
                    "margin_bottom": 35,
                    "corner_radius": 0,
                },
                "branding": {
                    "enabled": True,
                    "position": "top_left",
                    "font": "Montserrat-Medium.ttf",
                    "font_size": 22,
                    "text_color": "#AAAAAABB",
                    "background_color": "#00000000",
                    "padding_h": 0,
                    "padding_v": 0,
                    "margin_right": 35,
                    "margin_bottom": 30,
                    "corner_radius": 0,
                },
            }
        },
    },
}


def get_layout(layout_name: str) -> dict:
    """Get a layout preset by name. Returns the full layout dict including metadata."""
    if layout_name not in LAYOUTS:
        available = ", ".join(LAYOUTS.keys())
        raise ValueError(f"Unknown layout '{layout_name}'. Available: {available}")
    return LAYOUTS[layout_name]


def get_layout_config(layout_name: str) -> dict:
    """Get just the config portion of a layout for merging into thumbnail_config."""
    return get_layout(layout_name)["config"]


def list_layouts() -> list:
    """Return a summary list of all layouts for the AI to choose from."""
    result = []
    for key, layout in LAYOUTS.items():
        result.append({
            "id": key,
            "name": layout["name"],
            "description": layout["description"],
            "mood_tags": layout["mood_tags"],
        })
    return result
